import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { DataGrid, GridColDef, GridToolbar } from "@mui/x-data-grid";
import FormDialog from "../components/DialogForm";
import Grid from "../components/DataGrid";
import React from "react";

export default function Home() {
  const [userAddedRow, setUserAddedRow] = React.useState<FormData>();
  console.log("useraddedrow index");
  console.log({ userAddedRow });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <FormDialog
          sendFormData={(newRow: FormData) => setUserAddedRow(newRow)}
        />
        <Grid userAddedRow={userAddedRow} />
      </main>
    </div>
  );
}
